# Generated by Django 6.0.6 on 2026-06-08 04:54

import django.db.models.deletion
import portal.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('token', models.CharField(default=portal.models._generate_token, max_length=80, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, help_text="e.g. 'Mobile App' or 'Browser'", max_length=100)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_tokens', to='crm.contact')),
            ],
            options={
                'db_table': 'portal_token',
                'ordering': ['-created_at'],
            },
        ),
    ]
