# Generated by Django 6.0.6 on 2026-06-06 07:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('headline', models.CharField(default="Bangladesh's Most Trusted Technology Partner", max_length=200)),
                ('subheadline', models.TextField(default='We design, develop, and deploy world-class software, websites, and digital solutions for ambitious businesses')),
                ('primary_cta_text', models.CharField(default='Get a Free Consultation', max_length=50)),
                ('primary_cta_link', models.CharField(default='/contact', max_length=200)),
                ('secondary_cta_text', models.CharField(default='View Our Work', max_length=50)),
                ('secondary_cta_link', models.CharField(default='/portfolio', max_length=200)),
                ('gradient_start', models.CharField(default='#0066FF', max_length=20)),
                ('gradient_end', models.CharField(default='#00D9FF', max_length=20)),
                ('particle_count', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cms_hero_section',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=200)),
                ('simple_explanation', models.TextField()),
                ('icon_name', models.CharField(max_length=50)),
                ('gradient_from', models.CharField(default='#00D9FF', max_length=20)),
                ('gradient_to', models.CharField(default='#0066FF', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True)),
                ('cta_link', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'cms_services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('service_used', models.CharField(max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cms_testimonials',
                'ordering': ['order'],
            },
        ),
    ]
