# Generated by Django 6.0.6 on 2026-06-06 08:22

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('featured_image', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=100)),
                ('author_avatar', models.CharField(blank=True, max_length=500)),
                ('read_time', models.IntegerField(help_text='Minutes to read')),
                ('category', models.CharField(max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('views', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'cms_blog_posts',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('metric', models.CharField(max_length=100)),
                ('metric_description', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('challenge', models.TextField()),
                ('solution', models.TextField()),
                ('results', models.JSONField(default=list)),
                ('image_url', models.CharField(max_length=500)),
                ('logo_url', models.CharField(blank=True, max_length=500)),
                ('testimonial_quote', models.TextField()),
                ('testimonial_author', models.CharField(max_length=200)),
                ('testimonial_title', models.CharField(max_length=200)),
                ('technologies', models.JSONField(default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cms_case_studies',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('headline', models.CharField(default='Ready To Build Something Extraordinary?', max_length=200)),
                ('subtext', models.CharField(default="Let's discuss your project. Free 30-minute strategy call. No commitment. No pressure.", max_length=300)),
                ('primary_cta_text', models.CharField(default='Schedule Your Free Consultation', max_length=50)),
                ('primary_cta_link', models.CharField(default='/contact', max_length=200)),
                ('secondary_cta_text', models.CharField(default='Call Now', max_length=50)),
                ('secondary_cta_link', models.CharField(default='tel:+8801XXXXXXXXX', max_length=200)),
                ('background_gradient_start', models.CharField(default='#0066FF', max_length=20)),
                ('background_gradient_end', models.CharField(default='#00D9FF', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cms_cta_section',
            },
        ),
        migrations.CreateModel(
            name='Differentiator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cms_differentiators',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('icon_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('example_service', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cms_industries',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('icon_name', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cms_process_steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='TrustStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('numeric_value', models.IntegerField()),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cms_trust_stats',
                'ordering': ['order'],
            },
        ),
    ]
