# Generated by Django 6.0.6 on 2026-06-08 04:54

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_blogpost_casestudy_ctasection_differentiator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
