# Generated by Django 6.0.6 on 2026-06-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='long_description',
            field=models.TextField(blank=True, help_text='Full detail page body. HTML allowed.'),
        ),
        migrations.AddField(
            model_name='industry',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='service',
            name='currency',
            field=models.CharField(default='BDT', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='long_description',
            field=models.TextField(blank=True, help_text='Full detail page body. HTML allowed.'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='service',
            name='starting_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
