# Generated by Django 6.0.6 on 2026-06-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_industry_long_description_industry_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
