# Generated by Django 6.0.6 on 2026-06-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_industry_slug_alter_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='deliverables',
            field=models.JSONField(blank=True, default=list, help_text='List of strings, e.g. ["Discovery doc","Wireframes","Stakeholder map"]'),
        ),
        migrations.AddField(
            model_name='processstep',
            name='long_description',
            field=models.TextField(blank=True, help_text='Expanded detail shown on /process step detail or expand-on-hover'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='description',
            field=models.TextField(help_text='Short summary shown in process timeline'),
        ),
    ]
