# Generated by Django 6.0.6 on 2026-06-07 09:56

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('path', models.CharField(help_text='URL path this meta applies to. Use / for homepage, /about, /services/seo, etc.', max_length=300, unique=True)),
                ('title', models.CharField(help_text='Max 60 chars recommended for Google', max_length=70)),
                ('description', models.CharField(help_text='Max 155 chars recommended', max_length=200)),
                ('canonical_url', models.URLField(blank=True)),
                ('robots', models.CharField(choices=[('index,follow', 'Index, Follow'), ('noindex,follow', 'NoIndex, Follow'), ('index,nofollow', 'Index, NoFollow'), ('noindex,nofollow', 'NoIndex, NoFollow')], default='index,follow', max_length=30)),
                ('og_title', models.CharField(blank=True, max_length=100)),
                ('og_description', models.CharField(blank=True, max_length=300)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/')),
                ('og_type', models.CharField(default='website', max_length=30)),
                ('twitter_card', models.CharField(default='summary_large_image', max_length=30)),
                ('twitter_title', models.CharField(blank=True, max_length=100)),
                ('twitter_description', models.CharField(blank=True, max_length=300)),
                ('twitter_image', models.ImageField(blank=True, null=True, upload_to='seo/twitter/')),
                ('primary_keywords', models.JSONField(blank=True, default=list)),
                ('secondary_keywords', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'meta_tag',
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMetaTag',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('path', models.CharField(db_index=True, help_text='URL path this meta applies to. Use / for homepage, /about, /services/seo, etc.', max_length=300)),
                ('title', models.CharField(help_text='Max 60 chars recommended for Google', max_length=70)),
                ('description', models.CharField(help_text='Max 155 chars recommended', max_length=200)),
                ('canonical_url', models.URLField(blank=True)),
                ('robots', models.CharField(choices=[('index,follow', 'Index, Follow'), ('noindex,follow', 'NoIndex, Follow'), ('index,nofollow', 'Index, NoFollow'), ('noindex,nofollow', 'NoIndex, NoFollow')], default='index,follow', max_length=30)),
                ('og_title', models.CharField(blank=True, max_length=100)),
                ('og_description', models.CharField(blank=True, max_length=300)),
                ('og_image', models.TextField(blank=True, max_length=100, null=True)),
                ('og_type', models.CharField(default='website', max_length=30)),
                ('twitter_card', models.CharField(default='summary_large_image', max_length=30)),
                ('twitter_title', models.CharField(blank=True, max_length=100)),
                ('twitter_description', models.CharField(blank=True, max_length=300)),
                ('twitter_image', models.TextField(blank=True, max_length=100, null=True)),
                ('primary_keywords', models.JSONField(blank=True, default=list)),
                ('secondary_keywords', models.JSONField(blank=True, default=list)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical meta tag',
                'verbose_name_plural': 'historical meta tags',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSchemaOrg',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('path', models.CharField(help_text='URL path this schema applies to', max_length=300)),
                ('schema_type', models.CharField(choices=[('Organization', 'Organization'), ('LocalBusiness', 'LocalBusiness'), ('WebSite', 'WebSite'), ('WebPage', 'WebPage'), ('Article', 'Article'), ('BlogPosting', 'BlogPosting'), ('Service', 'Service'), ('Product', 'Product'), ('FAQPage', 'FAQPage'), ('BreadcrumbList', 'BreadcrumbList'), ('Person', 'Person'), ('Review', 'Review'), ('AggregateRating', 'AggregateRating')], max_length=50)),
                ('data', models.JSONField(help_text='Full JSON-LD block (without @context)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical schema org',
                'verbose_name_plural': 'historical schema orgs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SchemaOrg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('path', models.CharField(help_text='URL path this schema applies to', max_length=300)),
                ('schema_type', models.CharField(choices=[('Organization', 'Organization'), ('LocalBusiness', 'LocalBusiness'), ('WebSite', 'WebSite'), ('WebPage', 'WebPage'), ('Article', 'Article'), ('BlogPosting', 'BlogPosting'), ('Service', 'Service'), ('Product', 'Product'), ('FAQPage', 'FAQPage'), ('BreadcrumbList', 'BreadcrumbList'), ('Person', 'Person'), ('Review', 'Review'), ('AggregateRating', 'AggregateRating')], max_length=50)),
                ('data', models.JSONField(help_text='Full JSON-LD block (without @context)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'schema_org',
                'ordering': ['path', 'order'],
                'indexes': [models.Index(fields=['path'], name='schema_org_path_ce19db_idx')],
            },
        ),
    ]
