# Generated by Django 6.0.6 on 2026-06-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmediaasset',
            name='file_size',
            field=models.BigIntegerField(default=0, help_text='Bytes'),
        ),
        migrations.AddField(
            model_name='historicalmediaasset',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalmediaasset',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio'), ('other', 'Other')], default='image', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalmediaasset',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalmediaasset',
            name='width',
            field=models.IntegerField(blank=True, help_text='Pixels (images/videos)', null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='file_size',
            field=models.BigIntegerField(default=0, help_text='Bytes'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio'), ('other', 'Other')], default='image', max_length=20),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='width',
            field=models.IntegerField(blank=True, help_text='Pixels (images/videos)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmediaasset',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Required for images (SEO + accessibility)', max_length=300),
        ),
        migrations.AlterField(
            model_name='historicalmediaasset',
            name='file',
            field=models.TextField(help_text='Images, videos (mp4/webm), documents — no size limit. Replace anytime by uploading a new file here.', max_length=100),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Required for images (SEO + accessibility)', max_length=300),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(help_text='Images, videos (mp4/webm), documents — no size limit. Replace anytime by uploading a new file here.', upload_to='media/%Y/%m/'),
        ),
    ]
