# Generated by Django 6.0.6 on 2026-06-08 04:54

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0002_historicalmediaasset_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpage',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Rich-text editor — paste HTML or use toolbar'),
        ),
        migrations.AlterField(
            model_name='page',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Rich-text editor — paste HTML or use toolbar'),
        ),
    ]
