# Generated by Django 6.0.6 on 2026-06-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0003_alter_historicalpage_body_alter_page_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsitesettings',
            name='bing_verification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='gsc_verification',
            field=models.CharField(blank=True, help_text='Google Search Console site-verification token (content value only)', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='og_default_image',
            field=models.TextField(blank=True, help_text='Fallback OG/Twitter share image (1200x630 jpg). Used when a page has no og_image.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bing_verification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gsc_verification',
            field=models.CharField(blank=True, help_text='Google Search Console site-verification token (content value only)', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_default_image',
            field=models.ImageField(blank=True, help_text='Fallback OG/Twitter share image (1200x630 jpg). Used when a page has no og_image.', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='historicalsitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='GA4 measurement ID, e.g. G-XXXXXXX', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalsitesettings',
            name='google_tag_manager_id',
            field=models.CharField(blank=True, help_text='GTM container ID, e.g. GTM-XXXXX', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='GA4 measurement ID, e.g. G-XXXXXXX', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_tag_manager_id',
            field=models.CharField(blank=True, help_text='GTM container ID, e.g. GTM-XXXXX', max_length=50),
        ),
    ]
