# Generated by Django 6.0.6 on 2026-07-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0004_historicalsitesettings_bing_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmediaasset',
            name='cdn_url',
            field=models.URLField(blank=True, help_text='Cached CDN URL. Populated on upload; recomputed on file change.', max_length=600),
        ),
        migrations.AddField(
            model_name='historicalmediaasset',
            name='provider',
            field=models.CharField(choices=[('local', 'Local filesystem'), ('s3', 'AWS S3'), ('cloudinary', 'Cloudinary')], default='local', help_text='Which storage backend holds the bytes.', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalmediaasset',
            name='public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public_id (used for transformations + delete). Blank for local/S3.', max_length=300),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='cdn_url',
            field=models.URLField(blank=True, help_text='Cached CDN URL. Populated on upload; recomputed on file change.', max_length=600),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='provider',
            field=models.CharField(choices=[('local', 'Local filesystem'), ('s3', 'AWS S3'), ('cloudinary', 'Cloudinary')], default='local', help_text='Which storage backend holds the bytes.', max_length=20),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public_id (used for transformations + delete). Blank for local/S3.', max_length=300),
        ),
    ]
